version: '3'
services:
  sports_data_crawler:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/sports_data_crawler:0.1
    environment:
      DB_HOST: 192.168.2.3
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
