logging:
  level: DEBUG
DB:
  host: 192.168.2.3
  port: 3306
  schema: gambling_simulation
  user: user
  password: password
crawler:
  dateFormat: '%Y%m%d'
  urlPattern: https://www.playsport.cc/predictgame.php?action=scale&allianceid={game_type}&gametime={game_date}&sid={group_type}
data_updater:
  update_period: 24
